# Generated by Django 5.1.7 on 2025-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_address_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allocated_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('none', 'none'), ('Parklands', 'Parklands'), ('Upperhill', 'Upperhill'), ('South B/South C', 'South B/South C'), ('Buruburu/Donholm', 'Buruburu/Donholm'), ('long-distance', 'long-distance')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.CharField(choices=[('none', 'none'), ('Regina Auma', 'Regina Auma'), ('Elizabeth Okoth', 'Elizabeth Okoth'), ('Annette Kitagwa', 'Annette Kitagwa'), ('long-distance', 'long-distance')], default='antony', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
